- name: Install dependencies
  apt:
    force_apt_get: yes
    name:
      - gnupg2
      - software-properties-common
      - python3
      - python3-pip

- name: Add docker apt repository key.
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/raspbian/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/raspbian {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker
  apt:
    force_apt_get: yes
    name:
      - docker-ce:armhf
      - python3-setuptools
      - python3-pip
    install_recommends: no

- name: Install Docker SDK for python
  pip:
    name: docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

- name: Enable Docker IPv6
  copy:
    dest: /etc/docker/daemon.json
    mode: 0600
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "2001:db8:1::/64"
      }
  notify: Restart Docker

- name: Flush handlers
  meta: flush_handlers
